<?php

return [
    "links" => [
        ["ref" => "welcome",
        "name" => "Characters"],
        ["ref" => "welcome",
        "name" => "Comics"],
        ["ref" => "welcome",
        "name" => "Movies"],
        ["ref" => "welcome",
        "name" => "TV"],
        ["ref" => "welcome",
        "name" => "Games"],
        ["ref" => "welcome",
        "name" => "Collectibles"],
        ["ref" => "welcome",
        "name" => "Videos"],
        ["ref" => "welcome",
        "name" => "Fans"],
        ["ref" => "welcome",
        "name" => "News"],
        ["ref" => "welcome",
        "name" => "Shop"]
    ],

    "dc" => [
        ["ref" => "welcome",
        "name" => "Terms Of Use"],
        ["ref" => "welcome",
        "name" => "Privacy policy (New)"],
        ["ref" => "welcome",
        "name" => "Ad Choices"],
        ["ref" => "welcome",
        "name" => "Advertising"],
        ["ref" => "welcome",
        "name" => "Jobs"],
        ["ref" => "welcome",
        "name" => "Subscriptions"],
        ["ref" => "welcome",
        "name" => "Talent Workshops"],
        ["ref" => "welcome",
        "name" => "CPSC Certificates"],
        ["ref" => "welcome",
        "name" => "Ratings"],
        ["ref" => "welcome",
        "name" => "Shop Help"],
        ["ref" => "welcome",
        "name" => "Contact Us"],
        ["ref" => "welcome",
        "name" => ""],
    ],

    "sites" => [
        ["ref" => "welcome",
        "name" => "DC"],
        ["ref" => "welcome",
        "name" => "MAD Magazine"],
        ["ref" => "welcome",
        "name" => "DC Kids"],
        ["ref" => "welcome",
        "name" => "Dc Universe"],
        ["ref" => "welcome",
        "name" => "DC Power Visa"],
    ],

];
